# Generated by Django 5.1 on 2024-12-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='time_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='time_out',
            field=models.TimeField(blank=True),
        ),
    ]
