# Generated by Django 5.1 on 2024-10-09 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_project_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='created_by',
        ),
    ]
