# Generated by Django 5.1 on 2025-01-07 14:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_alter_project_time_in_alter_project_time_out'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='assign_employee',
        ),
        migrations.AddField(
            model_name='project',
            name='assign_employee',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
