# Generated by Django 5.1 on 2024-09-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_employeelocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_duration_start', models.DateField()),
                ('task_duration_end', models.DateField()),
                ('file_attachment', models.FileField(upload_to='')),
                ('task_name', models.CharField(max_length=250)),
                ('remarks', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
