# Generated by Django 5.1 on 2024-10-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_remove_project_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
